### ISSUE TITLE
[Question] Sample application using location history data

### ISSUE THREAD

**Issue by hossain-khan** [CarlosBergillos/LocationHistoryFormat#3]
This is a great initiative to document the location history data format spec.

Wondering if you or others have built anything using it and if there is a place to add those usage in this project to see those references.

**Comment by CarlosBergillos** [comment]
Glad you like the project!

I'm using the data and schema for personal projects, but there's definitely projects using Google location history data out there.
I haven't compiled any list of such projects though.

If we can come up with a good initial list maybe we could add them somewhere yeah!
Have you found example usages yourself for such a list?

**Comment by hossain-khan** [comment]
Sounds good! I haven't found any specific open-source project related to it. Though there exist few tools that allows you to visualize the takeout data but they were not open-source.

I am building a kotlin library based on the schema to parse these data. I also personally want to see visualized data on my phone using app. 

If I find something worthy of mentioning, I will try to come back and add something. Thanks
